server:
  port: 10600

spring:
  application:
    name: swagger-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.150:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"