server:
  port: 10100

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.150:8848
        namespace: deeaeca6-bed9-4fb1-b5b7-9c79278561ca
#        group: tianqingxiaozhu


service-url:
  nacos-provider: http://nacos-provider

management:
  endpoints:
    web:
      exposure:
        ## yml文件中存在特殊字符，必须用单引号包含，否则启动报错
        include: '*'

# feign 配置
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json # 压缩的请求类型
      min-request-size: 2048 # 压缩数据的下限
    response:
      enabled: true # 开启响应的zip压缩

  # 修改客户端的连接超时时间
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# 替换默认的URLConnection客户端，换成 httpclient，替换后上面配置的 连接超时时间就会失效
#  httpclient:
#    enabled: true
  okhttp:
    enabled: true
logging:
  level:
    com.tianqingxiaozhu.nacos.consumer.service: debug

