server:
  port: 10800
spring:
  application:
    name: gateway-swagger
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.150:8848
    gateway:
      routes: #配置路由路径
        - id: user-service
          uri: lb://swagger-user
          predicates:
            - Path=/swagger-user/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://swagger-order
          predicates:
            - Path=/swagger-order/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写